language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - pip install coveralls
    - pip install -r requirements.txt
script:
    - "python setup.py test"
after_success: coveralls
